[package]
name = "plz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
miette = { version = "5.3.0", features = ["fancy", "backtrace"] }
thiserror = "1.0.37"

nix = { version = "0.25", default-features = false, features = ["fs", "process", "term"] }
